apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patches:
  - target:
      group: projectcontour.io
      version: v1
      kind: HTTPProxy
      name: iris-red-app
    path: http-proxy-patch.yml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: iris-red-app
    path: deployment-patch.yml